spring:
  application:
    name: data-job
  profiles:
    active: '@activeProfile@'
  jmx:
    enabled: false
  cache:
    redis:
     key-prefix: k_job

server:
  port: 9002

info:
  app:
    name: "@project.name@"
    profile: "@activeProfile@"
    version: "@project.version@"
    description: "@project.description@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false

log4j2path: '@pom.log4j2.path@'

xxl:
  job:
    admin:
      #调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。
      #执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:

    #分别配置执行器的名称、ip地址、端口号
    #注意：如果配置多个执行器时，防止端口冲突
    executor:
      appname: data-job-executor
      ip: 127.0.0.1
      port: 9999

      #执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logpath: ${log4j2path}/job-log
      #执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
      #-1表示永不删除
      logretentiondays: -1

logging:
  config: classpath:log4j2-spring.xml
