spring:
  application:
    name: data-analysis
  profiles:
    active: '@activeProfile@'
  jmx:
    enabled: false
  cache:
    redis:
     key-prefix: k_analysis

server:
  port: 9001

info:
  app:
    name: "@project.name@"
    profile: "@activeProfile@"
    version: "@project.version@"
    description: "@project.description@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false

#mybatis配置
mybatis:
  mapper-locations: classpath:sql_mapper/*.xml
  type-aliases-package: com.hxcf.analysis.model.*
  configuration:
    call-setters-on-nulls: true
    use-generated-keys: true
    cache-enabled: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

#通用mapper配置
mapper:
  mappers: com.hxcf.common.generic.BaseMapper
  not-empty: false
  identity: MYSQL

#PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

logging:
  config: classpath:log4j2-spring.xml
